### ISSUE TITLE
Version update v0.6.0, add contributor section

### ISSUE THREAD

**Issue by FauconFan** [FauconFan/mdbook-cmdrun#14]
Thanks to @exsjabe, a new update will come soon!

New features:
- Windows support
- Inline regex

I'll also fix a few typos in the Readme, and update the dependencies before updating to v.0.6.0.

I would like to add a contributor section in the readme. @exsjabe , can I add your github tag on it? I'll wait your approval.

This is my way of thanking you for refreshing this project!

**Comment by exsjabe** [comment]
Sure I would like that! 😁

**Comment by FauconFan** [comment]
Here it goes!  
Ty again for refreshing this repo!  
This was very pleasant "working" with you on that! Hope I see you around!

**Comment by exsjabe** [comment]
I enjoyed working with you as well and in your repo, hope I see you too! 😄
