### ISSUE TITLE
Nixify the build system

### ISSUE THREAD

**Issue by Dauliac** [FauconFan/mdbook-cmdrun#16]
Hello,

I tried to use your extension from nix repository, with mdbook `0.4.37`, but I was faced with the need to update third-party dependencies,
Because of the lack of devops dev env, to simplify the cargo upgrade action, I nifixied the repository, to manage dependencies.

The build dans dev dependencies are now totally reproducible.

I added pre-commit hooks with [`lefthook`](https://github.com/evilmartians/lefthook) to shift left software delivery life cycle.

# Pull request:
resolve #17 

# TODO:
- [ ] nixify tests|

**Comment by FauconFan** [comment]
Hi, couldn't get around this issue earlier. Sorry for the delay.

Sorry, but I'm not familiar with NixOS and everything that goes with it. I looked into it a little bit, and it looks promising. But I don't see why I third-party dependency should adopt this philosophy. This repo should be "as simple as possible".
Feel free to fork the project and do whatever you like with it though.

Hope you understand
