### ISSUE TITLE
Assumption that working dir begins at `src` is not correct

### ISSUE THREAD

**Issue by kevinglasson** [FauconFan/mdbook-cmdrun#8]
https://github.com/FauconFan/mdbook-cmdrun/blob/ed334dc1cbc2f933e8e2546819d2e1a3ad446c5f/src/cmdrun.rs#L39

This is actually configurable in the `book.toml` for `mdbook` 

```toml
[book]
src = "path/to/src"
```

Otherwise I got it working nicely on MacOS

**Comment by FauconFan** [comment]
Ty for reporting this. I'll let anyone fix this, if he/she wants to. I can't do it myself right now, but it should be simple. One can use the `toml` crate I think.

Ty again for reporting this.

**Comment by FauconFan** [comment]
This has been resolved by @exsjabe in #12. Closing.
