### ISSUE TITLE
Is the \n necessary?

### ISSUE THREAD

**Issue by BrettWitty** [FauconFan/mdbook-cmdrun#9]
Requiring the `\n` in the regexp means that the cmdrun can't be put into a table or inline. Is there a way?

**Comment by FauconFan** [comment]
For now, the newline is hardcoded in the regex. So there is no way unfortunately. I mark this as a feature request.

**Comment by FauconFan** [comment]
This has been resolved by @exsjabe in #13. Thanks to him!
